-- Rename enum types to snake_case
ALTER TYPE "BeneficiaryRelationship" RENAME TO beneficiary_relationship;
ALTER TYPE "BenefitType" RENAME TO benefit_type;
ALTER TYPE "BulkImportRowStatus" RENAME TO bulk_import_row_status;
ALTER TYPE "ChangeRequestStatus" RENAME TO change_request_status;
ALTER TYPE "ChangeRequestType" RENAME TO change_request_type;
ALTER TYPE "ExternalClaimStatus" RENAME TO external_claim_status;
ALTER TYPE "FileCategory" RENAME TO file_category;
ALTER TYPE "ImportRowStatus" RENAME TO import_row_status;
ALTER TYPE "ImportStatus" RENAME TO import_status;
ALTER TYPE "ImportType" RENAME TO import_type;
ALTER TYPE "MemberStatus" RENAME TO member_status;
ALTER TYPE "MemberWorkflowAction" RENAME TO member_workflow_action;
ALTER TYPE "NotificationChannel" RENAME TO notification_channel;
ALTER TYPE "NotificationStatus" RENAME TO notification_status;
ALTER TYPE "RemovalReason" RENAME TO removal_reason;
ALTER TYPE "TransferStatus" RENAME TO transfer_status;
ALTER TYPE "UserRole" RENAME TO user_role;

-- Rename tables to snake_case
ALTER TABLE "AuditLog" RENAME TO audit_logs;
ALTER TABLE "Beneficiary" RENAME TO beneficiaries;
ALTER TABLE "BenefitAmount" RENAME TO benefit_amounts;
ALTER TABLE "BenefitPlanVersion" RENAME TO benefit_plan_versions;
ALTER TABLE "District" RENAME TO districts;
ALTER TABLE "ExternalClaimSubmission" RENAME TO external_claim_submissions;
ALTER TABLE "ImportJob" RENAME TO import_jobs;
ALTER TABLE "Member" RENAME TO members;
ALTER TABLE "MemberBulkImportRow" RENAME TO member_bulk_import_rows;
ALTER TABLE "MemberChangeRequest" RENAME TO member_change_requests;
ALTER TABLE "MemberOtpChallenge" RENAME TO member_otp_challenges;
ALTER TABLE "MemberSession" RENAME TO member_sessions;
ALTER TABLE "MemberTransfer" RENAME TO member_transfers;
ALTER TABLE "MemberWorkflowEvent" RENAME TO member_workflow_events;
ALTER TABLE "Notification" RENAME TO notifications;
ALTER TABLE "OrganizationSettings" RENAME TO organization_settings;
ALTER TABLE "OrganizationSettingsVersion" RENAME TO organization_settings_versions;
ALTER TABLE "RefreshToken" RENAME TO refresh_tokens;
ALTER TABLE "Region" RENAME TO regions;
ALTER TABLE "Report20Row" RENAME TO report20_rows;
ALTER TABLE "Spouse" RENAME TO spouses;
ALTER TABLE "StoredFile" RENAME TO stored_files;
ALTER TABLE "User" RENAME TO users;

-- Rename columns to snake_case
ALTER TABLE audit_logs RENAME COLUMN "actorId" TO actor_id;
ALTER TABLE audit_logs RENAME COLUMN "actorEmail" TO actor_email;
ALTER TABLE audit_logs RENAME COLUMN "entityType" TO entity_type;
ALTER TABLE audit_logs RENAME COLUMN "entityId" TO entity_id;
ALTER TABLE audit_logs RENAME COLUMN "beforeData" TO before_data;
ALTER TABLE audit_logs RENAME COLUMN "afterData" TO after_data;
ALTER TABLE audit_logs RENAME COLUMN "regionId" TO region_id;
ALTER TABLE audit_logs RENAME COLUMN "districtId" TO district_id;
ALTER TABLE audit_logs RENAME COLUMN "ipAddress" TO ip_address;
ALTER TABLE audit_logs RENAME COLUMN "userAgent" TO user_agent;
ALTER TABLE audit_logs RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE beneficiaries RENAME COLUMN "memberId" TO member_id;
ALTER TABLE beneficiaries RENAME COLUMN "fullName" TO full_name;
ALTER TABLE beneficiaries RENAME COLUMN "dateOfBirth" TO date_of_birth;
ALTER TABLE beneficiaries RENAME COLUMN "trusteeName" TO trustee_name;
ALTER TABLE beneficiaries RENAME COLUMN "trusteeGhanaCardId" TO trustee_ghana_card_id;
ALTER TABLE beneficiaries RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE beneficiaries RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE benefit_amounts RENAME COLUMN "planVersionId" TO plan_version_id;
ALTER TABLE benefit_amounts RENAME COLUMN "memberAmount" TO member_amount;
ALTER TABLE benefit_amounts RENAME COLUMN "spouseAmount" TO spouse_amount;
ALTER TABLE benefit_plan_versions RENAME COLUMN "effectiveFrom" TO effective_from;
ALTER TABLE benefit_plan_versions RENAME COLUMN "monthlyPremium" TO monthly_premium;
ALTER TABLE benefit_plan_versions RENAME COLUMN "collectionMethod" TO collection_method;
ALTER TABLE benefit_plan_versions RENAME COLUMN "createdById" TO created_by_id;
ALTER TABLE benefit_plan_versions RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE districts RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE districts RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE districts RENAME COLUMN "regionId" TO region_id;
ALTER TABLE external_claim_submissions RENAME COLUMN "memberId" TO member_id;
ALTER TABLE external_claim_submissions RENAME COLUMN "submittedById" TO submitted_by_id;
ALTER TABLE external_claim_submissions RENAME COLUMN "idempotencyKey" TO idempotency_key;
ALTER TABLE external_claim_submissions RENAME COLUMN "externalClaimId" TO external_claim_id;
ALTER TABLE external_claim_submissions RENAME COLUMN "formUrl" TO form_url;
ALTER TABLE external_claim_submissions RENAME COLUMN "errorCode" TO error_code;
ALTER TABLE external_claim_submissions RENAME COLUMN "errorMessage" TO error_message;
ALTER TABLE external_claim_submissions RENAME COLUMN "submittedAt" TO submitted_at;
ALTER TABLE external_claim_submissions RENAME COLUMN "lastSyncedAt" TO last_synced_at;
ALTER TABLE external_claim_submissions RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE external_claim_submissions RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE import_jobs RENAME COLUMN "fileId" TO file_id;
ALTER TABLE import_jobs RENAME COLUMN "uploadedById" TO uploaded_by_id;
ALTER TABLE import_jobs RENAME COLUMN "reportMonth" TO report_month;
ALTER TABLE import_jobs RENAME COLUMN "totalRows" TO total_rows;
ALTER TABLE import_jobs RENAME COLUMN "matchedRows" TO matched_rows;
ALTER TABLE import_jobs RENAME COLUMN "changedRows" TO changed_rows;
ALTER TABLE import_jobs RENAME COLUMN "unmatchedRows" TO unmatched_rows;
ALTER TABLE import_jobs RENAME COLUMN "duplicateRows" TO duplicate_rows;
ALTER TABLE import_jobs RENAME COLUMN "invalidRows" TO invalid_rows;
ALTER TABLE import_jobs RENAME COLUMN "errorMessage" TO error_message;
ALTER TABLE import_jobs RENAME COLUMN "startedAt" TO started_at;
ALTER TABLE import_jobs RENAME COLUMN "completedAt" TO completed_at;
ALTER TABLE import_jobs RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE import_jobs RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE import_jobs RENAME COLUMN "importedRows" TO imported_rows;
ALTER TABLE import_jobs RENAME COLUMN "readyRows" TO ready_rows;
ALTER TABLE members RENAME COLUMN "controllerId" TO controller_id;
ALTER TABLE members RENAME COLUMN "fullName" TO full_name;
ALTER TABLE members RENAME COLUMN "dateOfBirth" TO date_of_birth;
ALTER TABLE members RENAME COLUMN "ghanaCardId" TO ghana_card_id;
ALTER TABLE members RENAME COLUMN "report20Matched" TO report20_matched;
ALTER TABLE members RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE members RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE members RENAME COLUMN "districtId" TO district_id;
ALTER TABLE members RENAME COLUMN "createdById" TO created_by_id;
ALTER TABLE members RENAME COLUMN "phoneVerifiedAt" TO phone_verified_at;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "importJobId" TO import_job_id;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "rowNumber" TO row_number;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "controllerId" TO controller_id;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "fullName" TO full_name;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "districtName" TO district_name;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "districtId" TO district_id;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "dateOfBirth" TO date_of_birth;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "ghanaCardId" TO ghana_card_id;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "report20Matched" TO report20_matched;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "memberId" TO member_id;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "rawData" TO raw_data;
ALTER TABLE member_bulk_import_rows RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE member_change_requests RENAME COLUMN "memberId" TO member_id;
ALTER TABLE member_change_requests RENAME COLUMN "targetBeneficiaryId" TO target_beneficiary_id;
ALTER TABLE member_change_requests RENAME COLUMN "proposedData" TO proposed_data;
ALTER TABLE member_change_requests RENAME COLUMN "requestNote" TO request_note;
ALTER TABLE member_change_requests RENAME COLUMN "requestedById" TO requested_by_id;
ALTER TABLE member_change_requests RENAME COLUMN "reviewedById" TO reviewed_by_id;
ALTER TABLE member_change_requests RENAME COLUMN "reviewNote" TO review_note;
ALTER TABLE member_change_requests RENAME COLUMN "requestedAt" TO requested_at;
ALTER TABLE member_change_requests RENAME COLUMN "reviewedAt" TO reviewed_at;
ALTER TABLE member_change_requests RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE member_otp_challenges RENAME COLUMN "publicToken" TO public_token;
ALTER TABLE member_otp_challenges RENAME COLUMN "memberId" TO member_id;
ALTER TABLE member_otp_challenges RENAME COLUMN "otpHash" TO otp_hash;
ALTER TABLE member_otp_challenges RENAME COLUMN "expiresAt" TO expires_at;
ALTER TABLE member_otp_challenges RENAME COLUMN "maxAttempts" TO max_attempts;
ALTER TABLE member_otp_challenges RENAME COLUMN "consumedAt" TO consumed_at;
ALTER TABLE member_otp_challenges RENAME COLUMN "ipAddress" TO ip_address;
ALTER TABLE member_otp_challenges RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE member_sessions RENAME COLUMN "tokenHash" TO token_hash;
ALTER TABLE member_sessions RENAME COLUMN "memberId" TO member_id;
ALTER TABLE member_sessions RENAME COLUMN "expiresAt" TO expires_at;
ALTER TABLE member_sessions RENAME COLUMN "revokedAt" TO revoked_at;
ALTER TABLE member_sessions RENAME COLUMN "userAgent" TO user_agent;
ALTER TABLE member_sessions RENAME COLUMN "ipAddress" TO ip_address;
ALTER TABLE member_sessions RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE member_transfers RENAME COLUMN "memberId" TO member_id;
ALTER TABLE member_transfers RENAME COLUMN "fromDistrictId" TO from_district_id;
ALTER TABLE member_transfers RENAME COLUMN "toDistrictId" TO to_district_id;
ALTER TABLE member_transfers RENAME COLUMN "requestedById" TO requested_by_id;
ALTER TABLE member_transfers RENAME COLUMN "reviewedById" TO reviewed_by_id;
ALTER TABLE member_transfers RENAME COLUMN "activeKey" TO active_key;
ALTER TABLE member_transfers RENAME COLUMN "reviewNote" TO review_note;
ALTER TABLE member_transfers RENAME COLUMN "requestedAt" TO requested_at;
ALTER TABLE member_transfers RENAME COLUMN "reviewedAt" TO reviewed_at;
ALTER TABLE member_transfers RENAME COLUMN "effectiveAt" TO effective_at;
ALTER TABLE member_transfers RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE member_workflow_events RENAME COLUMN "memberId" TO member_id;
ALTER TABLE member_workflow_events RENAME COLUMN "fromStatus" TO from_status;
ALTER TABLE member_workflow_events RENAME COLUMN "toStatus" TO to_status;
ALTER TABLE member_workflow_events RENAME COLUMN "performedById" TO performed_by_id;
ALTER TABLE member_workflow_events RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE notifications RENAME COLUMN "idempotencyKey" TO idempotency_key;
ALTER TABLE notifications RENAME COLUMN "userId" TO user_id;
ALTER TABLE notifications RENAME COLUMN "memberId" TO member_id;
ALTER TABLE notifications RENAME COLUMN "maxAttempts" TO max_attempts;
ALTER TABLE notifications RENAME COLUMN "nextAttemptAt" TO next_attempt_at;
ALTER TABLE notifications RENAME COLUMN "providerMessageId" TO provider_message_id;
ALTER TABLE notifications RENAME COLUMN "lastError" TO last_error;
ALTER TABLE notifications RENAME COLUMN "sentAt" TO sent_at;
ALTER TABLE notifications RENAME COLUMN "readAt" TO read_at;
ALTER TABLE notifications RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE notifications RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE organization_settings RENAME COLUMN "singletonKey" TO singleton_key;
ALTER TABLE organization_settings RENAME COLUMN "portalName" TO portal_name;
ALTER TABLE organization_settings RENAME COLUMN "schemeSponsor" TO scheme_sponsor;
ALTER TABLE organization_settings RENAME COLUMN "sidebarMark" TO sidebar_mark;
ALTER TABLE organization_settings RENAME COLUMN "primaryColor" TO primary_color;
ALTER TABLE organization_settings RENAME COLUMN "accentColor" TO accent_color;
ALTER TABLE organization_settings RENAME COLUMN "memberIdLabel" TO member_id_label;
ALTER TABLE organization_settings RENAME COLUMN "reconciliationSource" TO reconciliation_source;
ALTER TABLE organization_settings RENAME COLUMN "subRegionLabel" TO sub_region_label;
ALTER TABLE organization_settings RENAME COLUMN "organizationEmail" TO organization_email;
ALTER TABLE organization_settings RENAME COLUMN "organizationPhone" TO organization_phone;
ALTER TABLE organization_settings RENAME COLUMN "websiteUrl" TO website_url;
ALTER TABLE organization_settings RENAME COLUMN "privacyNotice" TO privacy_notice;
ALTER TABLE organization_settings RENAME COLUMN "updatedById" TO updated_by_id;
ALTER TABLE organization_settings RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE organization_settings RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE organization_settings_versions RENAME COLUMN "settingsId" TO settings_id;
ALTER TABLE organization_settings_versions RENAME COLUMN "changedFields" TO changed_fields;
ALTER TABLE organization_settings_versions RENAME COLUMN "changedById" TO changed_by_id;
ALTER TABLE organization_settings_versions RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE refresh_tokens RENAME COLUMN "tokenHash" TO token_hash;
ALTER TABLE refresh_tokens RENAME COLUMN "userId" TO user_id;
ALTER TABLE refresh_tokens RENAME COLUMN "expiresAt" TO expires_at;
ALTER TABLE refresh_tokens RENAME COLUMN "revokedAt" TO revoked_at;
ALTER TABLE refresh_tokens RENAME COLUMN "userAgent" TO user_agent;
ALTER TABLE refresh_tokens RENAME COLUMN "ipAddress" TO ip_address;
ALTER TABLE refresh_tokens RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE regions RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE regions RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE report20_rows RENAME COLUMN "importJobId" TO import_job_id;
ALTER TABLE report20_rows RENAME COLUMN "rowNumber" TO row_number;
ALTER TABLE report20_rows RENAME COLUMN "controllerId" TO controller_id;
ALTER TABLE report20_rows RENAME COLUMN "fullName" TO full_name;
ALTER TABLE report20_rows RENAME COLUMN "districtName" TO district_name;
ALTER TABLE report20_rows RENAME COLUMN "ghanaCardId" TO ghana_card_id;
ALTER TABLE report20_rows RENAME COLUMN "memberId" TO member_id;
ALTER TABLE report20_rows RENAME COLUMN "rawData" TO raw_data;
ALTER TABLE report20_rows RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE spouses RENAME COLUMN "memberId" TO member_id;
ALTER TABLE spouses RENAME COLUMN "fullName" TO full_name;
ALTER TABLE spouses RENAME COLUMN "dateOfBirth" TO date_of_birth;
ALTER TABLE spouses RENAME COLUMN "ghanaCardId" TO ghana_card_id;
ALTER TABLE spouses RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE spouses RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE stored_files RENAME COLUMN "originalName" TO original_name;
ALTER TABLE stored_files RENAME COLUMN "storedName" TO stored_name;
ALTER TABLE stored_files RENAME COLUMN "mimeType" TO mime_type;
ALTER TABLE stored_files RENAME COLUMN "sizeBytes" TO size_bytes;
ALTER TABLE stored_files RENAME COLUMN "storagePath" TO storage_path;
ALTER TABLE stored_files RENAME COLUMN "downloadPath" TO download_path;
ALTER TABLE stored_files RENAME COLUMN "memberId" TO member_id;
ALTER TABLE stored_files RENAME COLUMN "spouseId" TO spouse_id;
ALTER TABLE stored_files RENAME COLUMN "uploadedById" TO uploaded_by_id;
ALTER TABLE stored_files RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE users RENAME COLUMN "fullName" TO full_name;
ALTER TABLE users RENAME COLUMN "isActive" TO is_active;
ALTER TABLE users RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE users RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE users RENAME COLUMN "regionId" TO region_id;
ALTER TABLE users RENAME COLUMN "districtId" TO district_id;
ALTER TABLE users RENAME COLUMN "passwordHash" TO password_hash;
